version: "3"

services:
  env-api-container:
    build: .
    environment:
      - number=0001
    networks:
      - env-api

  env-api-sidecar:
    build:
      context: .
      dockerfile: Dockerfile-sidecar
    ports:
      - "8888:8888"
    networks:
      - env-api

networks:
  env-api: {}
