version: "3"

services:
  db-container:
    build: .
    networks:
      - db

  db-sidecar:
    build:
      context: .
      dockerfile: Dockerfile-sidecar
    ports:
      - "7776:7776"
    networks:
      - db
      - zipkin_zipkin

networks:
  db: {}
  zipkin_zipkin:
    external: true
