version: "3"

services:
  web-container:
    build: .
    networks:
      - web

  web-sidecar:
    build:
      context: .
      dockerfile: Dockerfile-sidecar
    ports:
      - "9998:9998"
    networks:
      - web
      - zipkin_zipkin

networks:
  web: {}
  zipkin_zipkin:
    external: true
